spring.application.name=imagegalleryweb
spring.docker.compose.enabled=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:imagegallery 
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.error.whitelabel.enabled=false